### PR TITLE
Adds rotate_with_timer command

### PR DESCRIPTION
**Pull request by Digital-Learner**
Combines running the timer for a specified period of time and rotates the mobsters so driver/navigator change

### CODE REVIEW

**Comment by sublimecoder** [comment]
Looks like everything is good to go from the CI perspective. Rebase onto master and Pat should be able to merge this in.

**Comment by schmonz** [comment]
Since the `rotate_with_timer` branch is already pushed to mob's GitHub, I didn't want to rebase, just merge the latest `master` out to mob's `rotate_with_timer`. I've done that on my machine, but there are two problems:

7. I'm not permitted to push to mob to update the `rotate_with_timer` branch for this pull request
7. Even if I could, the integration test for our "rotate_with_timer 2" command is failing for me, probably because it's running against the installed gem, which probably doesn't include our new command, and if that's the case then I don't understand how to cause the installed gem to reflect our latest so that the test can potentially pass, or else how to run against our own code, and if I've misdiagnosed the problem entirely then something else is wrong.

**Comment by patmaddox** [comment]
I'll figure out 1. I will give core team members write access to the RubySteps repos. That way you can merge as needed.
That will also remove the need for the mob user... which creates the sort of problem we see here.
This all moves in the direction I want... more credit for more people, and more involvement and responsibility for those who volunteer.
I'm going to close this after I set up the core team with write access, to indicate that this pull request should occur from a personal account rather than mob.

**Comment by patmaddox** [comment]
@jendiamond @luisalima @Digital-Learner @sublimecoder @schmonz you all have core team invites... and should be able to handle pull requests for this repo from here on out

**Comment by patmaddox** [comment]
(as for 2, I'm pretty sure the tests run the dev version... so if the tests run the gem version anywhere that's an error)

**Comment by luisalima** [comment]
@patmaddox :+1:

**Pull request closed without merging**
